### ISSUE TITLE
显卡一直无法正常工作，显示7M显存

### ISSUE THREAD

**Issue by lostangelwangyang** [Shaw-fung/Intel-NUC8I5BEH-Hackintosh#1]
请教如果设置显卡驱动？

**Comment by Shaw-fung** [comment]
> 请教如果设置显卡驱动？

 我这里显卡完美驱动，你是使用我提供的EFI吗？然后将序列号修改为macmini 2018（Macmini8,1）。你参考一下。
![tu](https://user-images.githubusercontent.com/61656805/174520316-5350a187-c9cb-4073-8866-9a023616ecb3.png)
下面可以生产序列号，NUC8I5BEH用我提供的这个EFI只要修改好序列号就可以了。
![xuliehao](https://user-images.githubusercontent.com/61656805/174520658-0d79c38a-5f1b-4556-b8f4-04bcefad26d8.png)

**Comment by lostangelwangyang** [comment]
非常感谢，不知道为啥，我拔掉U盘，重新启动就ok了。
